using UnityEngine;
using System.Collections.Generic;

public class EventManage : MonoBehaviour
{
    // å‡¦ç†æ¸ˆã¿ã®ã‚¤ãƒ™ãƒ³ãƒˆå›æ•°ç­‰ã‚’è¨˜éŒ²ã™ã‚‹ã‚»ãƒƒãƒˆ
    // é«˜é€ŸãªãŸã‚HashSetã‚’ç”¨ã„ã‚‹
    public HashSet<int> processedEventCounts = new HashSet<int>();
    public HashSet<int> processedObjectMove = new HashSet<int>();
    public HashSet<int> processedPlayerMove = new HashSet<int>();

    void Update()
    {
        Debug.Log($"ğŸŒŸ:{GameRoot.I.seeking} ğŸ‘:{GameRoot.I.decision} â¤:{GameRoot.I.sensitive} ğŸ’­:{GameRoot.I.patience} ğŸ”:{GameRoot.I.insight}");

        // ã‚¤ãƒ™ãƒ³ãƒˆç·å®Ÿè¡Œå›æ•°ã«å¿œã˜ã¦å€‹æ€§å€¤å¢—åŠ 
        int currentEventCount = GameRoot.I.eventCount[0];
        if (!processedEventCounts.Contains(currentEventCount))
        {
            switch (currentEventCount)
            {
                case 5:
                case 10:
                case 15:
                case 20:
                case 25:
                    GameRoot.I.decision++;
                    GameRoot.I.insight++;
                    processedEventCounts.Add(currentEventCount);
                    break;
            }
        }

        // æœ¨ç®±ã€æ¨½ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’å‹•ã‹ã—ãŸæ™‚é–“ã«å¿œã˜ã¦å€‹æ€§å€¤å¢—åŠ 
        int currentObjectMove = GameRoot.I.objectMove;
        if (!processedObjectMove.Contains(currentObjectMove))
        {
            switch (GameRoot.I.objectMove)
            {
                case 100:
                case 500:
                case 1000:
                case 1500:
                case 2000:
                    GameRoot.I.seeking++;
                    processedObjectMove.Add(currentObjectMove);
                    break;
            }
        }

        // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ãŒç§»å‹•ã—ãŸæ™‚é–“ã«å¿œã˜ã¦å€‹æ€§å€¤å¤‰åŒ–
        int currentPlayerMove = GameRoot.I.PlayerMove;
        if (!processedPlayerMove.Contains(currentPlayerMove))
        {
            switch (GameRoot.I.PlayerMove)
            {
                case 2000:
                case 4000:
                case 6000:
                case 8000:
                case 10000:
                    GameRoot.I.seeking++;
                    GameRoot.I.sensitive++;
                    processedPlayerMove.Add(currentPlayerMove);
                    break;
            }
        }
    }
}
